### ISSUE TITLE
What are all of the types of XML files?

### ISSUE THREAD

**Issue by CYRiXplaysHalo** [CYRiXplaysHalo/CarnageReporter#1]
I only have Halo 1 MP installed, so do the following also generate XML game files?

- Halo 1 campaign
- Halo Reach campaign
- Halo Reach multiplayer
- Subsequent MCC PC releases.

If anyone has these titles, please check the following directory and show me what files you are seeing:
C:\Users\YOUR_WINDOWS_USER_NAME\AppData\LocalLow\MCC\Temporary

**Comment by Limited55** [comment]
Here is a list of my files, I even have the H3 flight installed. Hope this helps.

![image](https://user-images.githubusercontent.com/13245395/85589334-63af9b00-b63b-11ea-8f7c-a4720ed563ba.png)

**Comment by CYRiXplaysHalo** [comment]
Thank you. This issue is a little stale. The numbers at the end of each file represent the game version number, but not which game it is. There isn't version number overlap though so it's fine. Going to close this for now.
