### ISSUE TITLE
Update for 2024

### ISSUE THREAD

**Issue by theffapanda** [CYRiXplaysHalo/CarnageReporter#4]
Any interest in expanding this to work in 2024? 

I can grab it and make tweaks as well, but never hurts to ask. Thanks for the framework!

**Comment by CYRiXplaysHalo** [comment]
Does it not work anymore? Pretty sure it still does. I mean you're always open to create a branch. If you want to make a pull request I'm open to one, as long as it makes sense.

**Comment by theffapanda** [comment]
Hardcrashed when I tried H2A - best guess is related to the game IDs updating over the years?
Didnt have debug running and didn't dive into it too much admittedly.
If you still use it today and it functions fine then it may be user error and you can ignore me!

I grabbed icon6ix's branch and tested it for a bit.
Had to hardcode some of the paths from their instance (and they didnt have a check for the XML not existing) but after these tweaks so far so good. 

Curious if it will work on non-CE games, more to come.

**Comment by CYRiXplaysHalo** [comment]
Have you looked at this code? There's no way it's crashing the game and it isn't tied to game id's at all.

**Comment by theffapanda** [comment]
Its not crashing MCC - the exe closed after a Halo 3 matched ended and then fails to open due to some errors looking for non-existent files. 
I moved on to the other branch and was successful. Appreciate your time!

(If you ever decide to dig into it more, seems related to H3 Theater files)

**Comment by CYRiXplaysHalo** [comment]
Ah I see there is a release that does have an .exe. Yeah pretty much everyone who wanted to use this outside of me doesn't seem to know how to run a python script. It certainly could be updated to be a little bit better it just never got any real interest
